[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@latest",
  "cd ../.. && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["cd ../.. && BASE_PATH=/ pnpm --filter @workspace/tout-lissie run build"]

[start]
cmd = "PORT=$PORT pnpm --filter @workspace/tout-lissie run start"
